name: Deploy React App to VPS

on:
  push:
    branches:
      - deploy 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
      
      - name: Copy .env.config to .env
        run: cp .env.config .env

      - name: Build project
        run: npm run build
      
      - name: Cleanup old files
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "rm -rf /var/www/moviex-client/*"

      - name: Copy files to VPS via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist/**" # Thư mục chứa các file đã build
          target: "/var/www/moviex-client/" # Thư mục đích trên VPS

      - name: Restart nginx (nếu cần)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo systemctl reload nginx